from __future__ import annotations

import json
import os
from dataclasses import dataclass, field

from repo_to_shorts.kimi import _call_openrouter_api


@dataclass
class CreativeBrief:
    style: str
    title: str
    hook: str
    scenes: list = field(default_factory=list)
    music_mood: str = "ambient"
    total_duration: int = 60


def direct(repo_analysis: dict, model: str = "moonshotai/kimi-k2.6") -> CreativeBrief:
    """Kimi 2.6 creative director: analyze repo → output creative brief."""
    api_key = os.environ.get("OPENROUTER_API_KEY") or os.environ.get("KIMI_API_KEY")
    if not api_key:
        return _deterministic_fallback(repo_analysis)

    prompt = _build_director_prompt(repo_analysis)
    try:
        response = _call_openrouter_api(prompt, model, "https://openrouter.ai/api/v1")
    except Exception:  # noqa: BLE001 - fallback should preserve CLI reliability.
        return _deterministic_fallback(repo_analysis)

    return _parse_brief(response)


def _build_director_prompt(analysis: dict) -> str:
    """Build the creative director prompt from repo analysis."""
    return f"""You are a creative director for technical demo videos.
Given this repo analysis, create a creative brief for a 60-second short video.

REPO: {analysis.get('repo_name')}
DESCRIPTION: {analysis.get('description', '')}
LANGUAGE: {analysis.get('primary_language', '')}
KEY_FILES: {analysis.get('key_files', [])}
PURPOSE: {analysis.get('purpose', '')}

Output valid JSON:
{{
  "style": "dark-terminal|clean-academic|playful|cinematic",
  "title": "creative video title",
  "hook": "opening hook line (5-8 words, punchy)",
  "scenes": [
    {{
      "duration_seconds": 10,
      "visual_tool": "manim|pretext|ascii|svg",
      "narration": "narration text for this scene",
      "music_mood": "tension|reveal|energy|calm",
      "transition": "cut|fade|slide-left|zoom"
    }}
  ],
  "music_mood": "ambient|electronic|orchestral|minimal",
  "total_duration": 60
}}

Rules:
- 4-6 scenes, total ~60 seconds
- Hook scene first (5-8s, punchy)
- Vary visual_tool across scenes — don't use the same tool twice in a row
- Narration should tell a STORY about what this code ENABLES, not list files
- Style should match the repo's vibe (framework→clean-academic, game→playful, infra→dark-terminal, crypto→cinematic)
"""


def _deterministic_fallback(analysis: dict) -> CreativeBrief:
    """Fallback when no API key — still decent, not slop."""
    return CreativeBrief(
        style="dark-terminal",
        title=f"{analysis.get('repo_name', 'This Repo')}: What It Builds",
        hook="One repo. Infinite possibilities.",
        scenes=[
            {"duration_seconds": 8, "visual_tool": "pretext",
             "narration": f"{analysis.get('repo_name')} — let's see what it builds.",
             "music_mood": "tension", "transition": "fade"},
            {"duration_seconds": 15, "visual_tool": "svg",
             "narration": "Here's the architecture. Clean. Focused. Purpose-built.",
             "music_mood": "reveal", "transition": "cut"},
            {"duration_seconds": 20, "visual_tool": "manim",
             "narration": "Watch how the pieces connect. Each component has one job, and it does it well.",
             "music_mood": "energy", "transition": "slide-left"},
            {"duration_seconds": 12, "visual_tool": "ascii",
             "narration": "Under the hood: every line of code serves the mission.",
             "music_mood": "energy", "transition": "fade"},
            {"duration_seconds": 5, "visual_tool": "pretext",
             "narration": "repo-to-shorts: from code to creative short. Generated by Hermes Agent.",
             "music_mood": "calm", "transition": "fade"},
        ],
        music_mood="electronic",
        total_duration=60,
    )


def _parse_brief(content: str) -> CreativeBrief:
    """Parse JSON response from Kimi into CreativeBrief."""
    # Handle possible markdown code fences
    text = content.strip()
    if text.startswith("```json"):
        text = text[7:]
    if text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()

    data = json.loads(text)
    return CreativeBrief(
        style=data.get("style", "dark-terminal"),
        title=data.get("title", "Untitled"),
        hook=data.get("hook", ""),
        scenes=data.get("scenes", []),
        music_mood=data.get("music_mood", "ambient"),
        total_duration=data.get("total_duration", 60),
    )
